version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'daily'
      time: '13:00'
    open-pull-requests-limit: 300
    assignees:
      - luke-h1
