name: CI / test
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: luke-h1/setup-node@v2
        with:
          node-version: 14

      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Use latest npm version
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: format
        run: npm run format

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test

      - name: tsc
        run: npm run tsc
